### ISSUE TITLE
Deploy da Plataforma

### ISSUE THREAD

**Issue by robertotcestari** [codante-io/roadmap#4]
- [ ] Definição e Hospedagem do Front
- [ ] Definição e Hospedagem do Back

## Domínio e email
- [ ] Setup DNS domínio
- [ ] Setup Email (Google?)
- [ ] codante-io/roadmap#12
