### ISSUE TITLE
Arquitetura da Plataforma

### ISSUE THREAD

**Issue by robertotcestari** [codante-io/roadmap#5]
# Escolhas

### Backend
- [x] Laravel com Mysql e Redis
- [x] Qual será o domínio para a API? (api.codante.io)? 
- [x] Qual será o domínio para a área admin (api.codante.io/admin)?
Repo do Backend

_Por enquanto estou usando a branch `breeze-api` para fazer os testes. Basicamente é um scaffolding de API do laravel. Assim que puder já faço o merge na `main`_

### Frontend
- [x] NextJS 13 c/ Server Components
- [x] NextJS 13 s/ Server Components
- [x] Remix

# API

- [x] codante-io/roadmap#7 
- [x] codante-io/roadmap#11
- [x] codante-io/roadmap#8

# Front

### Autenticação 

- [x] #13
- [x] #14

# Outros Serviços

- [ ] codante-io/roadmap#12

**Comment by robertotcestari** [comment]
Feito. 
Optamos por Laravel no Back + Remix no Front

**Comment by robertotcestari** [comment]
CDN - Amazon S3
